version: "3.3"
services:
  app:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true